// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetwork.Data.Models;

namespace SocialNetwork.Data.Migrations
{
    [DbContext(typeof(SocialNetworkContext))]
    [Migration("20190207222204_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialNetwork.Data.Models.FollowersFollowed", b =>
                {
                    b.Property<int>("FollowerId");

                    b.Property<int>("FollowedId");

                    b.Property<int?>("FollowerUserId");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowerUserId");

                    b.ToTable("FollowersFollowed");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Edited");

                    b.Property<string>("StatusContent")
                        .IsRequired();

                    b.Property<DateTime>("StatusPostDate");

                    b.Property<int?>("UserId");

                    b.HasKey("StatusID");

                    b.HasIndex("UserId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserPictureUrl");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.FollowersFollowed", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.User", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SocialNetwork.Data.Models.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerUserId");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Status", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.User")
                        .WithMany("Status")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
